### ISSUE TITLE
Bugs with Luna and MA Ken

### ISSUE THREAD

**Issue by Ucross** [maphe/maphe.github.io#1]
Luna is doing way too much damage on her multiple strikes.  I think the multipliers should be .7, 1.4, and 2.1  but your calculator has her at like .7 to 7.0.

Also MA Ken does way too much damage on his S2.  I think his health decrease is scaling at like 10x the effectiveness

**Comment by maphe** [comment]
Thanks for raising it.

ML Ken has been fixed earlier this week, should be good now.

Regarding Luna I agree it's likely wrong, the datamined multiplier scales from 1 to 3 whereas in game she hits 3 to 10 times. I changed it to 1-3 for now as you asked, hope that gives better numbers.
