### ISSUE TITLE
Builds comparator

### ISSUE THREAD

**Issue by charodei** [maphe/maphe.github.io#10]
Hey, great tool! best dmg calculator ever seen. I have little suggestion for improvement: is it possible to implement memorising of few builds (atk, crDmg) to compare them in resulting table? Thanks!

**Comment by maphe** [comment]
Hey, thanks for the suggestion. I can think about it, not gonna promise anything though cause that might take a while to build it right.

But I definitely will keep that in mind going forward. Thanks

**Comment by maphe** [comment]
All right, sorry for the time it took, thanks for being patient, the build comparator is now up. Feel free to give me feedbacks directly on Discord if you have some.

**Comment by charodei** [comment]
Wow, works like a charm, good job :D This is better than I could imagine, thank you very much!
