### ISSUE TITLE
Damage Calculation Error

### ISSUE THREAD

**Issue by 3m0stargazer** [maphe/maphe.github.io#103]
SSB S2 doing less damage in-game than calculated on the tool. 

4263 atk 307 cdmg, maxed symbol, 10.2% imprint + 5% water gun, elemental advantage + atk up

vs w13 blaze dragona 

tool calculated s2 8035, in game actual damage 7775

same ~250 dmg difference when using other arts.

**Comment by maphe** [comment]
Hey, thanks for reaching out. You're actually not the first to raise that. I looked into it and couldn't figure out what's wrong. The multipliers are good, the base attack is good, so I'm not sure at this point where to look at.

Is it only the S2? If it's all 3 skills I might just have the Blaze Dragona's defense wrong.

**Comment by 3m0stargazer** [comment]
Hey Mathieu,

Yes, it's only the S2. S3 damage only differs by a single digit (ie 12224
calculated vs 12220 actual). I was testing oneshot so I have no data on s1.

I also tested with drink and the S2 damage is also strange, drink damage
seems to scale with def break. I have a strange feeling that it's the
actual code within the game that's sketchy (as always).

Thanks for reaching back anyway, you're doing god's work with the
calculator.

Rehards

**Comment by maphe** [comment]
I can reach out to SmileGate see what they have to say about it, although I'll have very low expectations... I'll keep you posted if I get anything worth sharing from them.

**Comment by 3m0stargazer** [comment]
Thank you, and good luck! I don't imagine they care that much – seeing as
they're just now fixing the SSB focus issue.

**Comment by ultimatespirit** [comment]
By the way, you get exactly 7,775 damage for those stats using 10.2% imprint (including the 0.2%) and ignoring water gun's effect altogether. Seems to imply SSB's S2 outright ignores water gun for some reason.

**Comment by 3m0stargazer** [comment]
﻿
﻿Hello! Thanks for your hard work, seems like it’s just a case of spaghetti code, like if water gun isn’t in effect when it’s the enemy’s turn. What’s new amirite
