### ISSUE TITLE
SSB S2 damage not calculated correctly

### ISSUE THREAD

**Issue by kevinshibuya** [maphe/maphe.github.io#106]
So I was trying to one-shot the first wave of W13, and for that my damage was 20262 (S3 + S2), my SSB stats were:

- ATK: 4415
- C.DMG: 303
- ATK IMPRINT: 10%
- ATK INCREASE: 5%
- With elemental advantage, increased atk, +21 symbol of unity, full mola.

My S3 dmg was 12230, only 1 of the calculation, but my S2 that should have been 8031, was somewhere around 7781.
So I think that something might be wrong with the dmg calc of SSB S2.

**Comment by maphe** [comment]
Hi, yeah this is a known issue. As far as I can tell it's a bug in game rather in than in the calculator. I've check the math several times as you're not the first one reporting it, but I couldn't find anything wrong in the calc, assuming the datamined multipliers are correct (0.7/1).

I opened a support ticket to SmileGate to report, but they just responded the usual "we'll let our developers know" and nothing after.

**Comment by kevinshibuya** [comment]
They just don't want to give us a compensation then lol, but I will also send a ticket just in case. Anyway I love this tool man, thx for your work.
