### ISSUE TITLE
賽柯貫穿套與3S套用

### ISSUE THREAD

**Issue by JamesHong-kdd** [maphe/maphe.github.io#107]
作者大你好
感謝大大更新貫穿套的係數0.15

但是在傷害計算時，3S DB計算的貫穿防禦%數，選到第7個DB時 (原技能貫穿+DB貫穿+貫穿套應該超過100%防禦了) 
一樣還有成長傷害，感覺略為不合理?   應該是6DB 60%+技能初始30%+15%貫穿就已超過100%
想求證一下是否為傷害計算錯誤XD 或是我理解貫穿防禦傷害計算的方式錯誤

感謝大大

**Comment by zx900930** [comment]
贯穿套与其它贯穿效果的叠加是乘算不是加算，所以7个debuff的时候仍不会超过100%, 只有在7个以上debuff的时候才会超过100%
