### ISSUE TITLE
Fighter Maya's S3 calc

### ISSUE THREAD

**Issue by Lanif2142** [maphe/maphe.github.io#110]
Hi Maphe, I found Fighter Maya's S3 calc issue when target has below 30% hp.

https://i.imgur.com/Jx7fVk3.png
this is damage image I was verifying.

now calc when target has below 30% hp:
(attack * 1.7 + def * 1.5) * crit damage * 1.871 * pow! * molagola * 300%

maybe this is correct calc?:
(attack * 1.7 + def * 1.5) * crit damage * 1.871 * pow! * molagola * **400%**

**Comment by maphe** [comment]
Thanks for pointing it out, should be fixed now.
