### ISSUE TITLE
Ravi S2 passive

### ISSUE THREAD

**Issue by superprincebro** [maphe/maphe.github.io#12]
Hello, I just wanted to ask if Ravi’s S2 passive has been updated in the calculator. Originally her damage scaled with Fighting Spirit, but after she was reworked her Demon’s Blood passive gives her 15% attack per stack (75% when maxed at 5 stacks). I’m not sure if it’s reflected on here, that’s why I’m asking. Thank you, I really appreciate all the work you do for this game!

**Comment by maphe** [comment]
Hey, thanks reaching out, it was simulated by the fact that 20 fighting spirit equals one attack stacked but since you pointed it out I fixed it so the form shows Attack Stack instead of Fighting Spirit. Damage output is gonna be the same though.
Thanks again, glad you like it.
