### ISSUE TITLE
BBK Caster HP% broken

### ISSUE THREAD

**Issue by Hezmana** [maphe/maphe.github.io#139]
When trying to adjust the caster hp% for blood blade karin moving the slider does not adjust the displayed percentage or the damage calculation. When clicking the plus or minus adjacent to the percentage the displayed percentage does not change but the damage calculation does. 
Browser: Waterfox G4.0.5.1
have not tested other browers

**Comment by maphe** [comment]
Hi, I can't quite reproduce the issue on Chrome, I don't know if it's a browser issue or something else. I'd advice to try on Chrome and see if you can have it working.

If it's still not working on Chrome please share the other fields that you have selected in the form, it could be a bug.
