### ISSUE TITLE
Target Template Issues

### ISSUE THREAD

**Issue by karuteru** [maphe/maphe.github.io#142]
By trying to optimize and calculate my W11 Alexa, I have come to realize the following issue:
After setting up all the data (Attack, CDMG%, DDJ+DDJ-Level, Elemental Advantage, Decreased Defense on Target) and then selecting the target (Here the W11 Wyvern or W13 Wyvern) the tool seems to load the wrong data internally - possibly the defense.

Inspecting the index.html has shown that the numbers are correct within the visible area (and transferred to the calculation?). But the following situation happens - Test Data as follows:

Alexa, Artifact DDJ, Manual settings
Attack 2119
Attack % Imprint 0, Attack % Increase 0
Critical Damage 275
Elemental Advantage set

Artifact Level 21

Target Wyvern 11 -> Wyvern
Decreaed Defense set
S1 on 3

On selecting the Wyvern the following numbers show in the tool 
S1: 17049
S1 Extra: 11385

Actual Data in a run for Alexa with said data:
S1: 13291
S1 Extra: 8896

After doing some trial and error I was able to closely reproduce those numbers:
Do the whole selection as before, then selecting the W11 Wyvern and the new steps are:
Decrease Defense by 1 (changing the selection to Manual)
Increase Defense by 1 (Still Manual but creating the original numbers for Wyvern as set by the template)
New calculated Damage for Alexa:
S1: 13115
S1 Extra: 8758

Which are like in a less than 5% margin of error in comparison to live data.

I was able to reproduce that issue with Firefox 95.0.2 and Safari 15.2 without fail every single time (Desktop)
(Firefox with multiple Extensions such as HTTPSeverywhere, uBlock Origin, Dark Reader
Safari without any Extensions)

Would it be possible if you could take a look into it? Or did I just configure it incorrectly?

Thank you in advance.

**Comment by maphe** [comment]
Hi, thanks for all the details.

First I think even the 5% gap you have at the end is still too much so I wouldn't even consider that to be correct. The calc should give you in-game numbers within a +/- 50 damage.

The Wyvern calculations have been pretty solid for a while and working fine as far as I'm aware, so before I dive into the code, I'd suggest you double-check:
- no other members of your team has an attack imprint release
- no other members has an team attack increase, like War Horn or the Water Gun

For context what happens when you drop defense by one and setting it back up by one, effectively it just removes the Wyvern from the target dropdown, hence the calculator stops adding the 30% extra damage from elemental advantage (on top of usual 10%) that hunt bosses have.

**Comment by karuteru** [comment]
Hey, thank you for your reply :)

My only imprints are Furious Team Crit Chance imprint and Alexa Team Attack Imprint (so Alexa only has the Crit Chance up herself)

Also my team has 2 DDJ + Egg of Delusion + Nostalgic Music box as Artifacts (which only buffs Barrier, Defense, Immunity or Heal)

Also if I understand it correctly - at least the huge differences - would have to be in a different direction (way lower than the actual numbers) if any imprint would increase it that much.
But yes, if the big calculation issue is gone and only the small margin still exists, then the damage should be more consistent, I agree. 
(I am not sure yet, from my little experience in the game - but do the attacks have their own little min/max damage gaps so that the damage might differ between 13100 and 13300 damage? So that only an average value would be calculated by the script?)

**Comment by maphe** [comment]
Yes, the damage would be even higher with imprints, you're right. I'm just so used to ask that cause it's usually the cause for a gap.

No, attacks don't have mix/max gaps, same stat will give same output of damage consistently on the same target.

Since you say you have little experience with the game, I wanna double-check a couple things:
- is your Alexa skill enhanced? the calculator by default assumes the heroes are +15 enhanced
- are you familiar with the critical hit mechanic in the game? and does your Alexa have 100% crit chance? (or 85% in the case of Wyvern)

**Comment by karuteru** [comment]
My Alexa is not +15, she is +8  (3/3/2) as I run with Skills inactive on her - is there a hidden boost once a character hits +15?

I am familiar with the mechanics as much as: +15% crit chance if elemental advantage, crit hit and damage takes priority over crushing, normal hits, etc.

Alexa is on her own at 79%  but I am running Furious in my team, upping the chance to 100% (Alexa has a speed of 157, Furious 194, so the cycle makes it ending up with an almost 100% uptime of the buff)

**Comment by maphe** [comment]
Ok, that's all good then, but I'm not sure where the gap comes from...

I just tried it with my own Alexa and numbers between the calc and the game are very close, so I'm still thinking there's some value that's entered wrong or missing in the calc.

Last thing I can do to try to help is if you wanna share a screenshot of your calculator page with everything setup and I can spot check if you missed something.

**Comment by karuteru** [comment]
This first image would be immediately after setting up my Alexa with the stats you can see and then selecting the wyvern.
The damage ends up with the 17049/11385.
![image](https://user-images.githubusercontent.com/21283244/149378578-504b4fff-0dbf-45a8-bbf4-c10f55bcc915.png)

Then after reducing the wyvern def by 1 it will only go up by a small amount (to 17057 and 11391). 
Once this is done I up it back up to 1255 the calculated damage ends up with 13115/8758.
Screenshot as follows:
![Screenshot 2022-01-13 at 18 23 08](https://user-images.githubusercontent.com/21283244/149379481-5bad18ba-0a01-416b-a8f3-fd078d6919c0.png)

Maybe I have done something terribly wrong, I do not know. But as of now it really confuses me, how those different numbers come up.

**Comment by maphe** [comment]
The gap between your first value and your second value is due to the Wyvern taking 30% extra damage from ice units. So that's by design.

The gap between what you see in the calc and what you see in the game, I can't really explain tbh.

**Comment by karuteru** [comment]
The gap between first and second value? Which one were you referring to? This confuses me a bit. (Especially as I have marked the elemental advantage in the calc as I know that there is a damage bonus (and defense bonus) for the elementally advantageous ones.

My main issue is still that the calculator has this huge gap in damage after selecting the wyvern and only correcting itself after lowering the def and returning it to its original value immediately after

**Comment by maphe** [comment]
Yeah that part is expected, if you look at Wyvern's skill, the first passive called "Fire's Protection" says "increases damage suffered from Ice elemental Heroes by 30%". The calculator takes that into account, if you select Wyvern in the dropdown, the extra 30% damage from ice heroes is applied.

**Comment by karuteru** [comment]
Okay. In terms of the calculator this makes a lot of sense. Thank you for that explanation. 

Then I am honestly confused where my input was wrong. As I only get close to real numbers if I do enforce the calculator internal removal of the 30% buff. 
Might it be possible that I'm using a wrong attack stat? (I've been using the calculated combined attack value as per this screenshot:
![image](https://user-images.githubusercontent.com/21283244/149461192-8a153d37-1917-4a11-ad7a-dc612b416a2b.png)
A mistake input on my side there would be the only issue left being the reason for the calculation to be off so badly 

(I really really appreciate the time you put into your project and in assisting trying to find a solution. Thank you!)

**Comment by maphe** [comment]
I don't see anything wrong here either. I'm kinda running out of ideas. If you want feel free to record a run and I can check the video and see if you missed anything in game. Other than that I'm just as confused as you.

**Comment by karuteru** [comment]
Hey. Sorry for not having posted an update yet, but from reading the newest patch notes for the upcoming patch I might have an idea why the calculator has been off for the last few days (or actually not off):
6. Other Improvements and Adjustments
Monsters
- An issue where the "increase damage suffered from ice elemental heroes by 30% and "when a non ice elemental heros turn ends, increases the casters combat readiness by 10% effects of Wyvern Hunt 11 boss Onix Wyverns passive skill Fire's Protection were not applied correctly will be corrected
So if I read this correctly, the game has been miscalculating damage for a while now, crippling W11 damage (as I started playing W12 last weekend I was already surprised that my DDJ damage suddenly spiked as well)

**Comment by maphe** [comment]
Ok that makes me feel a bit better already, feel free to give it another try after the patch and see if things finally align 🤞

**Comment by karuteru** [comment]
I plan on doing that. Will do a quick 11 run tonight to get me a few old numbers and see the new numbers then in comparison

**Comment by karuteru** [comment]
I have done runs pre and post patch now and it is now obvious that the calculation was bugged in game and not on your side.

Alexa Damage Snapshot pre Patch:
2280 ATK, 294 CDMG
S1 at +3, advantages, etc vs W11
14248 + 9430

Post Patch:
18522 + 12259

**Comment by maphe** [comment]
well that's a relief, thanks for confirming
