### ISSUE TITLE
Commander Lorina Damage inaccuracy

### ISSUE THREAD

**Issue by hyrio** [maphe/maphe.github.io#146]
i use she in Caides13..
s3 skill damage is not correct when she attacked Converted Symaqus. in calculator if damage is 100, but in game the last damage is 100 * 1.2 = 120. 
s1 skill damage is not correct when she attacked caides. in calculator damage is large compare it to the game. i found the calculator damage it is added 75% ATK(s2 skill) by default.
when i set Attack % Increase -75%, the damage，that is almost right.

**Comment by Pollockmaster** [comment]
I agree with this, her damage is overstated against Caides in the calculator. I am not sure it is 75% overstated though (and it looks quite close on Synaqus, I am not getting the overstatement by 20% per above comment.

My example is C Lorina with 4298 attack, 277 C damage, 4.8% attack increase from card of small miricles, DDJ +30, Rage set, Attack buff, elemental advantage ticked. Skills max 'molad'. 

Caides, target debuff, first attack (so s2 scaling at first level) is a dual from camilla who does exactly 2000 damage. C Lorina damage in calculator is 27170. Actual damage is 22372 (having minused 2000, total damage was 24372). 82.34% of expected damage

Next hit includes the first scaling of the s2, calculator damage is 28353, actual damage is 23571. 83.13% of expected damage.

I am not sure what causes the scaling difficulty here, but clearly the calculator is overstating the damage.

**Comment by tyopoyt** [comment]
I know this is quite old now but this may have been due to the calculator not taking Caides' HP Damage reduction into account.  I recently fixed this on my version of the calc (https://e7calc.xyz/)

If you see this and still have a similar issue feel free to let me know on my repo: https://github.com/tyopoyt/epic7-damage-calc
