### ISSUE TITLE
W11 stats are wrong

### ISSUE THREAD

**Issue by vsub** [maphe/maphe.github.io#149]
SG shadow buff wyvern 11 few months ago and now when I input my stats,I get wrong damage values
W11 now have more hp,I don't know about the defense

**Comment by maphe** [comment]
I don't have the updated stats, so the best I can do would be to remove W11 from the boss list

**Comment by vsub** [comment]
When I do the calculation,it seems the values are the same(or almost the same if I did it the wrong way)if I just manually set the wyvern hp to the new one
I think the defense is the same,just the hp is higher and DDJ is doing more damage to the boss because of it

**Comment by maphe** [comment]
I fixed the HP, hope that helps
