### ISSUE TITLE
Add vigor or attack buff to target

### ISSUE THREAD

**Issue by RealWei** [maphe/maphe.github.io#154]
Hi,

There are more and more skills that calculates damage based on the target's attack/defense.
Is it possible to add vigor or attack buff to target so that I can calculate how much defense/hp I need?

For example, I want to build an Aravi with vigor buff that can defense LQC, or a high attack character with attack/vigor buff that can defense Straze.

Thank you.

**Comment by maphe** [comment]
Seems doable, let me look into it...

**Comment by maphe** [comment]
Ok, that's fine, I'll release that at the same time as Jack-O' whenever I get access to her multipliers (so probably not today)

**Comment by RealWei** [comment]
Looking forward to the update. Thanks a lot.

**Comment by maphe** [comment]
Done
