### ISSUE TITLE
Add El's Fist artifact damage calculator

### ISSUE THREAD

**Issue by twquan1** [maphe/maphe.github.io#16]
I had found out that this artifact is missing on the calculator, could you add it to the artifact list?

I had found about the condition it needed to activate the artifact at reddit, hope it is helpful to u :)
https://www.reddit.com/r/EpicSeven/comments/asbwme/els_fist_numbers/

and Thx for the work you done for e7 community! :D

**Comment by maphe** [comment]
Done. Thanks for sharing the numbers, that's all I was missing. Feel free to give it a try and let me know if you see any issue.

**Comment by maphe** [comment]
I forgot to mention I only considered the attack increase from the artifact, not sure if there's any warrior hero that has speed scaling damage, but if there is that won't be included in the formula at this point.
