### ISSUE TITLE
Ludwig's S3 skill multiplier is wrong

### ISSUE THREAD

**Issue by Pengua** [maphe/maphe.github.io#165]
S3 multiplier is listed at 0.85, but testing shows it to be around 0.9.

**Comment by maphe** [comment]
Hi, I'm using the multipliers that have been datamined. Are you sure you're not missing an attack imprint or an attack increase artifact in your math? that would inflate the damage numbers

**Comment by Pengua** [comment]
Yes, I triple checked the numbers.
Ludwig under Vigor + Attack buff + 5% CoSM hitting naked B13 boss. 4842atk/263cd

Expected S3 Value: 13149
Actual S3 Value: 13935

Increase of ~5.7%, the same increase as .85 -> .90 multi.

**Comment by maphe** [comment]
what artifact? also make sure to check elemental advantage

I'm pretty confident the multipliers are correct, they got re-datamined recently with Ludwig's buff, so there must be some tweaks to make in the input on the calc

**Comment by Pengua** [comment]
He's holding a book, so no artifact as well as no imprints. I manually did the number calculations myself to reach .90 multi. I can record and send a video of everything if you want to see yourself. Again, I triple checked everything.

**Comment by Pengua** [comment]
Removing his S3 EE (I don't think that's the issue):

4673atk/263cd, same buffs, same target:

Expected S3 Value: 11814
Actual S3 Value: 12521

Increase of ~5.98%, still approximately 0.85 -> 0.90.

**Comment by maphe** [comment]
Might be a Banshee specific mechanic, I don't know, or might also be a bug 🤷‍♂️ I'll see if I can have the datamine double checked whenever there's a new hero released to be datamined

**Comment by maphe** [comment]
All right, sorry for the wait, finally got verified via datamine and confirmed, I'll update to 0.9 when I take care of the whole balance patch update in the calc
