### ISSUE TITLE
jsdelivr's CDN certificates expired

### ISSUE THREAD

**Issue by EricMoIr** [maphe/maphe.github.io#185]
All the requests going to jsdelivr to fetch font awesome, bootstrap, jquery, etc are failing because the certificates for the subdomain expired today. If you have a local version of the scripts, maybe you could upload them to the repo and have github host them alongside the rest of the tool's scripts?
![image](https://github.com/maphe/maphe.github.io/assets/21262614/7e835d4f-6938-46f2-ae0d-d4fdab13b8b7)

Otherwise this is how the site looks as it stands
![image](https://github.com/maphe/maphe.github.io/assets/21262614/da7f534a-6528-4e5f-a89f-476a54edcaf7)

**Comment by maphe** [comment]
I'm not maintaining it anymore, feel free to check out https://e7calc.xyz and https://beta.e7calc.xyz if you want an up to date calculator

**Comment by EricMoIr** [comment]
> I'm not maintaining it anymore, feel free to check out https://e7calc.xyz and https://beta.e7calc.xyz if you want an up to date calculator

I see. Well, the first link has the same issue, but fortunately the second one is self hosting the scripts. Thank you! I'll close the issue
