### ISSUE TITLE
Daydream Joker

### ISSUE THREAD

**Issue by AlexeiA** [maphe/maphe.github.io#2]
The artifacts' list doesn't include Daydream Joker.

**Comment by maphe** [comment]
hi @AlexeiA I just added it, feel free to give it a try, hopefully the math are correct. Let me know if you notice any issue.

**Comment by AlexeiA** [comment]
Thank you for the quick response! But I get wrong results. Maybe it is because DDJ's target's HP is capped at 50K by it's controls (but if I enter value manually it seems to be working). Also target's HP desn't chage when I choose W11 from the targets list.
For reference, S1 of +15 Karin with +24 DDJ, 3484 ATK and 217% Crit Damage and 7.2% ATK imprint makes 7935 crit damage.

**Comment by maphe** [comment]
yeah, the slider caps at 50k but you can enter any value manually.

Auto setting target's max HP when selecting a hunt boss is definitely something I'm gonna do but I want to add the 3 missing bosses first, for which I couldn't find the defense values yet.

Also be aware that ice heroes deal an extra 30% damage to the Wyvern, that the calculator doesn't support yet. Same thing, I'd like to complete the hunt boss list before working on that.

Feel free to reach out on discord if you have more feedbacks suggestions. Discord would also work if you wanna help me working on DDJ's math, send screenshots and stuff.
Thanks for the help.

**Comment by AlexeiA** [comment]
Have tested against Banshee 11, she has about 1849 defence and 60,624 HP. S1 of my Karin from above makes 3222 crit damage, but the calculator returns 3091. Not a very big difference, can be floating point   and rounding issues, but maybe something is wrong in the formula. Also I'll double check B11 defence value later.
