### ISSUE TITLE
Cdom S2 stacks damage are wrong

### ISSUE THREAD

**Issue by Breadmaker-san** [maphe/maphe.github.io#3]
Currently, each stack of S2 adds about 20% to her total damage, but each S2 stack gives only 7.02% of her gear attack (ignoring the buffs) as a flat modifier attack so damage boost can't be so high.

**Comment by maphe** [comment]
Hi @Breadmaker-san thanks for raising it, I just pushed a fix, let me know if numbers look better now.

I was applying 54% per stack instead of 5.4%, and I was not even applying at the right place in the formula. Should be good now.

**Comment by Breadmaker-san** [comment]
Better, but skill data sheet have misleading tooltip, before raising a bug I did some testing and found out that 7,02% damage boost works only if enemy have about 0 def, with higher defense enemies math and test numbers match only if you treat her stacks as +7.02% attack buff for each stack, like hell cutter, I will send some ss I have on my phone with tests and math, can send more later when I'll be at my pc.

**Comment by Breadmaker-san** [comment]
Fixed now, thank you.
