### ISSUE TITLE
Mirsa s3 skill up

### ISSUE THREAD

**Issue by daisy3000** [maphe/maphe.github.io#33]
Hi,

I noticed that the skill up's on Mirsa's s3 look to be incorrect on skillup's +4, 5 and 6. Currently the damage is being increased by 5% per level, but it should actually be 10% for +4 and 5 and 15% for +6. The damage looks like it's being skilled up by 5% but I haven't done the math to see if it's just a graphical bug or the calculation is wrong. Just thought I would give you a heads up and thanks for the site, I use it daily!

**Comment by maphe** [comment]
Hey, thanks you for reaching out, good catch. I just fixed it.
