### ISSUE TITLE
Pavel's S3 doesn't have an option to ignore damage-sharing effects

### ISSUE THREAD

**Issue by Nell13** [maphe/maphe.github.io#35]
Currently Pavel's S3 is calculated with the defined Damage Transfer %. His S3 should ignore this value when attacking a non-Elite/Boss opponent. It would be nice if there was some kind of "Opponent is Elite/Boss" toggle to determine whether or not it should ignore the transfer % when calculating damage.

**Comment by maphe** [comment]
I see what you mean, but honestly I feel like users can just set the damage transfer to 0% manually when looking at his S3's damage. It's true that would be a nice thing to have so you don't even have to think about it, but it'd be a bit of an overhead for me to implement whereas there's an easy workaround in the UI.

I'll keep the ticket open though, so I can revisit later if ever I think about a smooth way to make that work.

**Comment by maphe** [comment]
Forgot to close that but I fixed it a while back.
