### ISSUE TITLE
ML Leo Bomb calculation doesn't take elemental advantage into account when selected on the damage calculator.

### ISSUE THREAD

**Issue by Synch7** [maphe/maphe.github.io#58]
I have just tested it in game:
-ML Leo bombs are affected by element advantage: 
1993 attack ML Leo did exactly 3200 damage on the Light boss from Chapter 1 stage 9-1. Which is an exact 15% increase in damage.
-No attack buff was applied and no Molagoras (as if anyone ever Molaed ML Leo pre-future buff)
-Artifact used was Guiding Light teammate/rep was Luna. 
-No def break  was active on the boss.
-Soulburn was used for the extra turn, which shouldn't affect damage.

Sorry for the terrible reporting format, this is my first "bug" report.

**Comment by maphe** [comment]
Interesting. Thanks for reporting. Could you just add more details about the target's defense? You mention a 15% increase, but not sure what we're comparing it to.

If confirmed, I'll look into implementing a fix in the calculator.

**Comment by maphe** [comment]
Also elemental advantage give a 10% damage increase, 15% would come from a Target debuff.

**Comment by Synch7** [comment]
Oh I apologize for that one: the 15% was compared to the damage displayed on the online damage calculator which shows 2798 damage when i enter 1994 in the attack value.
So I just divided the number I saw on the website by the value I got in game.

**Comment by maphe** [comment]
Cool thanks for the details. Good thing to consider as you test it further is the target defense; usually mock battling in RTA with a friend so you know their defensive stats.

**Comment by Synch7** [comment]
Here is some context, though I just realized that since the two units I am comparing damage for probably have different defense values as you said.
Which means this might be a whole lot of nothing.
You are right RTA is probably the only area where I could check given that none of the hunts main bosses are Light element and Light alter has her defense mechanic.
I'll let you know if I try, though I play on Asia server and don't speak with anyone in game so probably unlikely.
Thank you for an amazing website all the same!
![Screenshot_20200728-221026](https://user-images.githubusercontent.com/68924532/88722928-f1414780-d11f-11ea-9286-748f739a6af8.jpg)
![Screenshot_20200728-221135](https://user-images.githubusercontent.com/68924532/88722935-f3a3a180-d11f-11ea-9b30-1f82c67d9c89.jpg)
![Screenshot_20200728-221023](https://user-images.githubusercontent.com/68924532/88722940-f56d6500-d11f-11ea-9031-c7131411c074.jpg)

**Comment by maphe** [comment]
RTA mock rooms being cross server now, feel free to add me on Discord and we can experiment together when we find some common time.

**Comment by Synch7** [comment]
Sure thing, let's set up something and try. I'll do that
