### ISSUE TITLE
Charles

### ISSUE THREAD

**Issue by Randsanity** [maphe/maphe.github.io#6]
Charles skill 2 damage is off.

Tried with stats: 2700 atk and 250 crit damage, calculator says 13k but outputs 18k in-game.

**Comment by maphe** [comment]
What enemy are you fighting? (he has a 30% extra elemental damage on banshee)
How many debuffs on target?
Do you have any attack imprint in your team?

Feel free to reach out on Discord and we can try to figure it out.
Thanks

**Comment by Randsanity** [comment]
Banshee 11.

Pretty sure I checked all the things needed there.

: Atk buff, def break, elemental adv, number of buffs, number of enemy, and artifact.

Like right now for example is says 12k damage but im dealing 17k damage (2577 atk, 259 crit damage, +0 tonfa, 3 buffs, def broken banshee)
