### ISSUE TITLE
ML Leo's S2 Damage

### ISSUE THREAD

**Issue by BaneOfSmite** [maphe/maphe.github.io#60]
According to his skill, his s2 should have increase damage when target is debuff'd

**Comment by maphe** [comment]
I see that on his S1 but not on his S2 🤔 

> Fires a shockbomb at the enemy, with an 80% chance to increase skill cooldown by 1 turn. Decreases skill cooldown of Go, Racoo! by 1 turn. At the end of the turn, detonates bombs inflicted on the enemy.

**Comment by BaneOfSmite** [comment]
Oh wait I read his awakening wrong, sorry my bad
