### ISSUE TITLE
Purrgis S2 damage does not depend on caster's max health

### ISSUE THREAD

**Issue by ringoroadagain** [maphe/maphe.github.io#61]
I found that Purrgis S2 (Counter) damage does not depend on caster's max health on the calculator. This is different from the actual.

**Comment by maphe** [comment]
Hi, sorry took a bit of time to check the game database. Wanted to double check since I received mixed informations about him.

Looks like you're right, so I'll update later today.
Thanks for bringing it up.

**Comment by maphe** [comment]
Fixed

**Comment by ringoroadagain** [comment]
Thank you for the response and fix.
Now S1 and S2 (Counter) damage are same on the calculator but this is still different from the actual.
S2 (Counter) damage should be lower than S1's though I'm sorry but I don't have the formula for him.

**Comment by maphe** [comment]
Sorry for the delay, I was waiting for the data. Should be good now.
