### ISSUE TITLE
Gunther Bleed Increase

### ISSUE THREAD

**Issue by DiscworldDeath** [maphe/maphe.github.io#65]
Gunther has a character-specific checkbox to increase S3 damage if target has bleed, but that is no longer in his kit.

**Comment by maphe** [comment]
Thanks for raising that, looks like it's been wrong for a long time... I'm gonna look for his "new" multipliers and fix as soon as I get them (all my usual resources for multipliers have it wrong).

**Comment by maphe** [comment]
Fixed.
