### ISSUE TITLE
Cidd's S1 Damage

### ISSUE THREAD

**Issue by Lanif2142** [maphe/maphe.github.io#68]
Cidd's S1 should be ignore additional damage bonus from S2 when without speed buff.

**Comment by maphe** [comment]
Not sure I understand the issue, when "increased speed" is not checked, Cidd's S1 multipliers are 0.9/1.35, when it's checked they become 1.05/1.35

Am I missing something?

**Comment by Lanif2142** [comment]
Thanks for your reply
Multipliers is fine. but now, without "speed increase" buff, S1 damage is increased by S2 skill level
I think S2 skill damage bonus is only valid when with "increased speed" buff

**Comment by maphe** [comment]
Got it, thanks for catching that. This is fixed now.
