### ISSUE TITLE
Defense calc has problems?

### ISSUE THREAD

**Issue by Lanif2142** [maphe/maphe.github.io#69]
Hi, thanks for the calculator. i love it.

I think Defense calc could be wrong.
for ex, Defense 1000 with Aurius (Defense 10% Increase) and Decreased Defense (Defense 70% Decrease)

calculator in game is as follows
　1000 * (1.0 + 0.1 - 0.7) = 400

But the calculator is as follows
　1000 * (1.0 + 0.1) * (1.0 - 0.7) = 330

please check this. thanks!

**Comment by zx900930** [comment]
Didn't test the def buff with def down.
But I'm sure when they're 2 negative effects. 
Exp: def down 70% with def pen 50%
The def ingame was
(Def*0.3)*0.5 
Not Def*(1-0.7-0.5)

**Comment by maphe** [comment]
I double checked the current formula, what @Lanif2142 said seems to align with how I calculate defUp+defDown.

I just pushed a fix for combining defUp/defDown with the defUp% slider. Should work as expected now.
