### ISSUE TITLE
REQUEST* attack down debuff option to be added

### ISSUE THREAD

**Issue by ruiz** [maphe/maphe.github.io#71]
Hey, this is not really an issue, but I couldn't find an option to raise a feature request. Is it possible to add the attack down debuff to the damage calculations? Thanks!

**Comment by zx900930** [comment]
This is really wired, if you are running a cleave team, you won't get debuffed before doing the damage.
But you could apply attack*0.5 as your attack input manually.

**Comment by maphe** [comment]
Yeah you can workaround it with the attack% slider. That being said I'm open to add an Attack Down checkbox. I'll look into it.

**Comment by maphe** [comment]
Done
