### ISSUE TITLE
Radiant Forever Artifact

### ISSUE THREAD

**Issue by shukafu** [maphe/maphe.github.io#82]
issues:
 1. the artifact's effect applies on all mobs which **it shouldn't** and should only apply to bosses and elite mobs.  
 2. the artifact's effect also applies even on a single target skill which **it shoudn't** and should only apply to AoE skills

**Comment by maphe** [comment]
Thanks for raising it up, I'll fix the AoE part of it sometime during the weekend. The Boss and Elite part though I'll leave it up the the users to know what they're doing, that's too much effort for me to implement vs little effort for the user.

I'll let you know when the AoE is fixed.

**Comment by maphe** [comment]
Done, sorry for the delay, Abyss got in my way...
