### ISSUE TITLE
Cermia/Riolet S3 with pen set calculation

### ISSUE THREAD

**Issue by mikenguyen92** [maphe/maphe.github.io#84]
I've heard the defense pen set works multiplicatively with Riolet/Cermia S3 interactions, but it seems as though the calculator additively calculates this with pen set giving incorrect values. This is assuming the interactions are multiplicative of course, if they are additive then I don't see an issue.

**Comment by maphe** [comment]
Thanks for the heads up, if you know where I can see some in-game screenshots that demonstrate that I'd appreciate it. I just don't wanna go back and forth between additive or multiplicative based on claims. If you can confirm that should be an easy fix then.

I'll try to confirm it on my own as well.

**Comment by maphe** [comment]
I got confirmation. This is fixed now.
