### ISSUE TITLE
Selection Box’s Too Large

### ISSUE THREAD

**Issue by DntStv23** [maphe/maphe.github.io#85]
Hey Maphe. First off I'd like to thank you for making such a great tool for us E7 Gamers :)

I'd like to bring to your attention that the selection boxes are way too large on my iPhone 6s and may be a bug. I've attached a photo. Thanks in advance!

![image](https://user-images.githubusercontent.com/75266265/100634561-21039480-3338-11eb-9633-1a63780ceafa.png)

**Comment by maphe** [comment]
Hi. Thank you. Yeah somebody reported something similar after last Wed's release, not sure what happened I haven't been able to reproduce the issue so far (also I don't have an iPhone). I'll take another look tonight.

Do you know if you've upgraded your Safari Browser recently? I wonder if it has something to do with that... Also feel free to use Chrome until I figure it out, it should be working fine.

**Comment by DntStv23** [comment]
I appreciate the response:)
I'll run some tests. Thank you!

**Comment by zx900930** [comment]
Unfortunately, 3rd party browsers(including chrome) under iOS still using Safari's webview.
And the debug for a dev without a iOS devices or Mac is painful unless you paid for a cloud device service.

**Comment by maphe** [comment]
Ah so doesn't work either on Chrome/iPhone?

Seems like a recent issue tho, so something must have changed in iOS... I'll try at least upgrading the library responsible for the dropdown, maybe they patched it 🤷‍♂️

**Comment by zx900930** [comment]
@maphe you could use https://www.browserstack.com/ to test.
The iphone 12 seems ok
![image](https://user-images.githubusercontent.com/734749/100639008-f49a4900-3334-11eb-84e6-b67942574168.png)
And XR is ok, too
![image](https://user-images.githubusercontent.com/734749/100639179-24495100-3335-11eb-976e-22c336811bb8.png)

**Comment by DntStv23** [comment]
I'm on the latest update 14.2 on my iPhone 6s. When I first went on the site over a month ago, it didn't have this problem :/

**Comment by maphe** [comment]
@DntStv23 any luck that it fixed itself or that a browser/os upgrade helped?

I upgraded the dropdown library to the latest version but I don't expect much from that... Somebody else reported similar issue and they fixed by changing some privacy settings; although it was Firefox on Windows 10 so probably not related.

**Comment by DntStv23** [comment]
Thanks for checking in. No luck, still the same. I've tried many things. I'm sure it will work itself out one of these days. Thank you :)
