### ISSUE TITLE
Epic Seven Damage Calculator Bug - Damage Reduction

### ISSUE THREAD

**Issue by chocky1022** [maphe/maphe.github.io#86]
Hello,

I was using the e7 damage calculator and I believe I have found a bug. I was doing tests on Dark Corvus S3 damage which is supposed to be reduced by damage reduction (such as aurius etc), but then I realized draco plate was listed under damage reduction. I selected draco plate and realized that the calculator shows that it decreases the damage of dcorvus' s3 when it shouldn't (since his s3 doesn't crit, and draco plate only reduces the damage of critical hits). I think draco plate was mistakenly put under damage reduction when there's cases that it works differently from other sources of DR.

Sincerely,
Beeg

**Comment by maphe** [comment]
Ah you're right, I'll move it out of the list. I didn't implement anything regarding damage reduction that only affects critical hits, so that might be confusing. I'll take it out and people can still manually enter the value with the slider if they still wanna check.

Thanks for pointing it out.

**Comment by chocky1022** [comment]
Cool, thanks for the quick reply! Appreciate your work for the community
