### ISSUE TITLE
hero selection dropdown empty

### ISSUE THREAD

**Issue by RyanPatrick26** [maphe/maphe.github.io#88]
not sure if anyone else is having an issue with this, but whenever the hero selection dropdown just doesn't have anything i can select, even when i type in the name of a hero

screenshots for reference
![Screenshot 2020-12-10 083359](https://user-images.githubusercontent.com/22944519/101778950-97379200-3ac2-11eb-931a-ab0da6a80750.png)
![Screenshot 2020-12-10 083617](https://user-images.githubusercontent.com/22944519/101779087-ca7a2100-3ac2-11eb-9e26-1cf2d4033fd1.png)

**Comment by RyanPatrick26** [comment]
nvm, think it was an issue on my end, it's fixed itself

**Comment by maphe** [comment]
Hi, glad it worked itself out. Do you mind sharing how you fixed it? In case people reach out to me with the same problem, you're not the first one running into this and I'm not sure what to tell them...

**Comment by RyanPatrick26** [comment]
i think it might have just fixed itself, and is now actually not working again

**Comment by RyanPatrick26** [comment]
looks like it might be that it doesn't play nice with some browser extensions

**Comment by RyanPatrick26** [comment]
![image](https://user-images.githubusercontent.com/22944519/101992279-19b98080-3c80-11eb-9c2e-2950627fcd5e.png)
browser extension might not be the case, but it is working when i refresh the page while inspecting the element

**Comment by babayanv** [comment]
Doesn't work for me either

Firefox 83.0 (64-bit) for Ubuntu canonical - 1.0

I don't have any extensions installed. Seem to be that way after the latest firefox update

Works fine on my phone through chrome

**Comment by maphe** [comment]
The little feedback I had so far implied either updating Windows 10 with the last upgrade and/or turning off Firefox "Enhanced Tracking Protection".

I just installed Firefox so I can reproduce and investigate further, I'll see if I can come up with a better fix but you can try those for now...

**Comment by maphe** [comment]
I just pushed a tentative fix. Let me know how it goes on your end...

**Comment by babayanv** [comment]
Seem to be working fine

**Comment by maphe** [comment]
Cool, I'll take it. Still not quite sure what was happening, I'm just gonna blame sub-optimized browsers whereas Chrome was doing the job just fine.
