### ISSUE TITLE
Damage calculation mismatch with Time matter artifact on Mistychain wave with Vivian

### ISSUE THREAD

**Issue by robertoll** [maphe/maphe.github.io#91]
The damage reported on calculator is higher than in game. The difference is around 2k. Does not happen with Portrait.

**Comment by maphe** [comment]
Hi, could you give me some more details about the issue? Maybe provide some screenshots from the calculator and in game so I can have a better understanding of what I should look at in the code?

Thank you

**Comment by robertoll** [comment]
https://imgur.com/a/xhr7oWP

**Comment by robertoll** [comment]
Video shows 12k damage instead of 13k with Time matter

https://user-images.githubusercontent.com/9343776/104135925-ddea0780-5360-11eb-8f05-8104112f59d6.mp4

**Comment by maphe** [comment]
OK, I think what's happening is that your Time Matter hasn't proc'd yet when Vivian uses her S2. Time Matter procs on a kill and she doesn't kill until she uses her S2. The extra damage from Time Matter will apply to the next Vivian's S1 (assuming it stays between wave 1 and wave 2 of the battle).

**Comment by robertoll** [comment]
So, the damage calculation assumes the after effects of the Time matter during the initial calculation?

**Comment by maphe** [comment]
Correct, if you select Time Matter on the calculator, it will give you damage after Time Matter has proc'd, so next attack after a kill.
