### ISSUE TITLE
Epic 7 Damage Calculator Bug

### ISSUE THREAD

**Issue by teehee00** [maphe/maphe.github.io#92]
Assassin Cidd's Skill 1 only has +30% damage increase from skill ups, however your damage calculator shows that it has a +35% damage increase.

When +2 his Skill 1, it gives him an extra 5% to defense break, instead of +5% damage increase. 

The information from [http://epic7x.com/character/assassin-cidd/](url) seems to be incorrect.

The image attached is Assassin Cidd's Skill 1 enhancement, from the game.
![a cidd s1](https://user-images.githubusercontent.com/76818628/103416356-40a10d80-4bc1-11eb-99b4-225ffcd1ecd4.png)

**Comment by maphe** [comment]
Hi, thanks for letting me know. This is fixed now 👍
