### ISSUE TITLE
C Merc DDJ Bug

### ISSUE THREAD

**Issue by Frostulfr** [maphe/maphe.github.io#94]
After selecting Celestial Mercedes and Daydream Joker together, then changing to any other artifact, the Damage section at the bottom only displays her S1 damage. Selecting another hero with any artifact except DDJ and then going back to C Merc does seem to reset it until you select DDJ with her again. The only other way to correct is to reload the page entirely. If you select her with any other artifact first it will display properly, until you do the above mentioned.
Screenshot of issue added.
![Screenshot 2021-01-09 210001](https://user-images.githubusercontent.com/77211446/104108725-d83be580-52be-11eb-817c-9aced04c96be.png)

**Comment by maphe** [comment]
Hi, I cannot manage to reproduce the bug. Can you make sure it still happens after clearing your browser cache or from the incognito mode?

If it's still happening after that, do you mind telling me what OS/browser combination you're using?
Thanks

**Comment by Frostulfr** [comment]
Hey, tried in Incognito and cleared cache for the site. Same results. I don't think I explained how to reproduce it very well. Let me put it step by step.
Reload page
Select any hero from drop down (except for C Merc)
Select Daydream Joker
Select C Merc
Select any other artifact

That's how I get the screenshot above. If I reselect DDJ it shows all 3 skills again, if I switch to any other artifact again, it shows only S1.
Occurs on both my PC and phone.
Windows 10 and Chrome, both up-to-date
Android 11 (One UI 3.0) and Chrome, both up-to-date

**Comment by maphe** [comment]
Thanks for the step by step, it was a tricky use case. That should be fixed now (hopefully the fix didn't break anything else).

Let me know if you see any other issue.
